apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: connector-import-document
  name: connector-import-document
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: connector-import-document
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.28.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/aks-opencti-default: "true"
        io.kompose.service: connector-import-document
    spec:
      containers:
        - env:
            - name: CONNECTOR_AUTO
              value: "true"
            - name: CONNECTOR_CONFIDENCE_LEVEL
              value: "15"
            - name: CONNECTOR_ID
              value: ${CONNECTOR_IMPORT_DOCUMENT_ID}
            - name: CONNECTOR_LOG_LEVEL
              value: info
            - name: CONNECTOR_NAME
              value: ImportDocument
            - name: CONNECTOR_ONLY_CONTEXTUAL
              value: "false"
            - name: CONNECTOR_SCOPE
              value: application/pdf,text/plain,text/html
            - name: CONNECTOR_TYPE
              value: INTERNAL_IMPORT_FILE
            - name: CONNECTOR_VALIDATE_BEFORE_IMPORT
              value: "true"
            - name: IMPORT_DOCUMENT_CREATE_INDICATOR
              value: "true"
            - name: OPENCTI_TOKEN
              value: ${OPENCTI_ADMIN_TOKEN}
            - name: OPENCTI_URL
              value: http://opencti:8080
          image: opencti/connector-import-document:5.8.2
          name: connector-import-document
          resources: {}
      restartPolicy: Always
status: {}
