# REDIS STORAGE
#
# STATUS: UNTESTED
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: redisdata
  name: redisdata
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25G
status: {}
